### ISSUE TITLE
Add instructions for re-enabling search suggestions?

### ISSUE THREAD

**Issue by 0rphee** [Tagggar/Firefox-Alpha#14]
I really prefer having search suggestions enabled, and though the theme is great (thanks! its really nice), I went through a good time searching how could I style them somewhat decently. I finally ended up with this:

So I thought that it could be really nice to add this to the readme so others have the chance to choose :)
```css

#urlbar-input-container {
  opacity: 0;
}

vbox.urlbarView {
  color: var(--tab-selected-textcolor);
  background-color: var(--tab-selected-bgcolor);
}
```

https://github.com/Tagggar/Firefox-Alpha/assets/79347623/65b95fb7-6736-42ae-9474-80cb739e898e

https://github.com/Tagggar/Firefox-Alpha/assets/79347623/4020be4d-eb3b-4eed-b78d-c809722f5a71
