### ISSUE TITLE
Expose urlbar "shield" icon, to access ETP menu

### ISSUE THREAD

**Issue by AeliusSaionji** [Tagggar/Firefox-Alpha#8]
The shield provides quick access to toggling `Enhanced Tracking Protection` on a given website.

I searched around and there seems to be no other way to invoke this menu, best as I can tell.

**Comment by AeliusSaionji** [comment]
It doesn't need to be visible, as long as it exists and I can `shift-tab space` from the urlbar to trigger it.

![image](https://github.com/Tagggar/Firefox-Alpha/assets/4342746/2d9401ee-f77f-47e4-a2c1-00fd3dad9f64)

**Comment by AeliusSaionji** [comment]
I was able to do just that, replacing this line

https://github.com/Tagggar/Firefox-Alpha/blob/78bf9a9ea57538b0a58212731e81dea80d490105/chrome/userChrome.css#L77

with this

```css
#urlbar-zoom-button,#identity-box,
#tracking-protection-icon-container {
  z-index: -1 !important;
}
```
